Imports System.Windows

Namespace Views

    ''' <summary>
    ''' Code-behind for the main window. Deliberately empty apart from
    ''' InitializeComponent: in strict MVVM the view has no logic - state and
    ''' behavior live in MainViewModel, injected as DataContext by the
    ''' composition root (Application.xaml.vb).
    ''' </summary>
    Partial Public Class MainWindow
        Inherits Window

        Public Sub New()
            ' Generated by the XAML compiler; loads and wires up the XAML.
            InitializeComponent()
        End Sub

    End Class

End Namespace
